version: '2'

services:
  keycloak:
    build: ./keycloak
    environment:
      KEYCLOAK_USER: administrator
      KEYCLOAK_PASSWORD: administrator
    ports:
      - "9090:8080"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"